# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.0.5.dev640+gc28f2fda0.d20230823'
__version_tuple__ = version_tuple = (3, 0, 5, 'dev640', 'gc28f2fda0.d20230823')
